import React, { useState } from 'react';
import { motion, AnimatePresence } from 'framer-motion';
import { X, FileText, Loader2, Sparkles, Save } from 'lucide-react';
import { aiService } from '../../services/aiService';
import { useAuth } from '../../hooks/useAuth';
import toast from 'react-hot-toast';

// Sydney Avatar Component
const SydneyAvatar = ({ className = "w-5 h-5" }: { className?: string }) => (
  <div className={`${className} bg-gradient-to-br from-purple-500 to-pink-500 rounded-full flex items-center justify-center`}>
    <svg viewBox="0 0 24 24" fill="none" className="w-3/4 h-3/4 text-white">
      <path d="M12 2C13.1 2 14 2.9 14 4C14 5.1 13.1 6 12 6C10.9 6 10 5.1 10 4C10 2.9 10.9 2 12 2Z" fill="currentColor"/>
      <path d="M21 9V7L15 1H5C3.89 1 3 1.89 3 3V7H1V9H3V15C3 16.1 3.9 17 5 17V19C5 20.1 5.9 21 7 21H9C10.1 21 11 20.1 11 19V17H13V19C13 20.1 13.9 21 15 21H17C18.1 21 19 20.1 19 19V17C20.1 17 21 16.1 21 15V9H21ZM7 3H15L19 7V15H5V3H7Z" fill="currentColor"/>
    </svg>
  </div>
);

interface SessionSummaryModalProps {
  isOpen: boolean;
  onClose: () => void;
  sessionId: string;
  sessionName: string;
}

const SessionSummaryModal: React.FC<SessionSummaryModalProps> = ({
  isOpen,
  onClose,
  sessionId,
  sessionName,
}) => {
  const { user } = useAuth();
  const [summary, setSummary] = useState('');
  const [isGenerating, setIsGenerating] = useState(false);
  const [hasGenerated, setHasGenerated] = useState(false);

  const generateSummary = async () => {
    if (!user) return;

    setIsGenerating(true);
    try {
      const generatedSummary = await aiService.generateSessionSummary(sessionId, user.id);
      setSummary(generatedSummary);
      setHasGenerated(true);
      toast.success('Session summary generated by Sydney!');
    } catch (error) {
      toast.error('Failed to generate summary');
      console.error('Summary generation error:', error);
    } finally {
      setIsGenerating(false);
    }
  };

  const saveSummary = () => {
    // In a real implementation, you might want to save this to the database
    // For now, we'll just copy to clipboard
    navigator.clipboard.writeText(summary);
    toast.success('Summary copied to clipboard!');
  };

  const handleClose = () => {
    setSummary('');
    setHasGenerated(false);
    onClose();
  };

  return (
    <AnimatePresence>
      {isOpen && (
        <motion.div
          initial={{ opacity: 0 }}
          animate={{ opacity: 1 }}
          exit={{ opacity: 0 }}
          className="fixed inset-0 bg-black/50 backdrop-blur-sm flex items-center justify-center p-4 z-50"
          onClick={handleClose}
        >
          <motion.div
            initial={{ opacity: 0, scale: 0.95, y: 20 }}
            animate={{ opacity: 1, scale: 1, y: 0 }}
            exit={{ opacity: 0, scale: 0.95, y: 20 }}
            onClick={(e) => e.stopPropagation()}
            className="bg-slate-800 rounded-xl border border-slate-700 w-full max-w-2xl max-h-[80vh] overflow-hidden"
          >
            {/* Header */}
            <div className="flex items-center justify-between p-6 border-b border-slate-700">
              <div className="flex items-center">
                <div className="bg-gradient-to-br from-purple-600 to-pink-600 rounded-full p-2 mr-3">
                  <FileText className="w-5 h-5 text-white" />
                </div>
                <div>
                  <h2 className="text-xl font-semibold text-white">Sydney's Session Analysis</h2>
                  <p className="text-slate-400 text-sm">{sessionName}</p>
                </div>
              </div>
              <button
                onClick={handleClose}
                className="p-2 text-slate-400 hover:text-white transition-colors"
              >
                <X className="w-5 h-5" />
              </button>
            </div>

            {/* Content */}
            <div className="p-6 overflow-y-auto max-h-[60vh]">
              {!hasGenerated ? (
                <div className="text-center py-12">
                  <SydneyAvatar className="w-16 h-16 mx-auto mb-6" />
                  <h3 className="text-lg font-semibold text-white mb-2">
                    Generate AI Analysis
                  </h3>
                  <p className="text-slate-400 mb-6 max-w-md mx-auto">
                    Let Sydney analyze your trading session and provide comprehensive insights about your performance, 
                    patterns, and recommendations for improvement.
                  </p>
                  <button
                    onClick={generateSummary}
                    disabled={isGenerating}
                    className="inline-flex items-center px-6 py-3 bg-gradient-to-r from-purple-600 to-pink-600 text-white rounded-lg hover:from-purple-700 hover:to-pink-700 transition-all disabled:opacity-50"
                  >
                    {isGenerating ? (
                      <>
                        <Loader2 className="w-5 h-5 mr-2 animate-spin" />
                        Sydney is analyzing...
                      </>
                    ) : (
                      <>
                        <Sparkles className="w-5 h-5 mr-2" />
                        Generate Analysis
                      </>
                    )}
                  </button>
                </div>
              ) : (
                <motion.div
                  initial={{ opacity: 0, y: 20 }}
                  animate={{ opacity: 1, y: 0 }}
                  className="space-y-4"
                >
                  <div className="bg-slate-700 rounded-lg p-4 border border-slate-600">
                    <div className="flex items-center mb-3">
                      <SydneyAvatar className="w-6 h-6 mr-2" />
                      <span className="text-purple-400 font-medium text-sm">Sydney's Analysis</span>
                    </div>
                    <div className="prose prose-invert max-w-none">
                      <div className="text-slate-100 whitespace-pre-wrap leading-relaxed">
                        {summary}
                      </div>
                    </div>
                  </div>
                  
                  <div className="flex justify-between items-center pt-4">
                    <p className="text-slate-400 text-sm">
                      Analysis generated by Sydney • {new Date().toLocaleDateString()}
                    </p>
                    <button
                      onClick={saveSummary}
                      className="inline-flex items-center px-4 py-2 bg-blue-600 text-white rounded-lg hover:bg-blue-700 transition-colors"
                    >
                      <Save className="w-4 h-4 mr-2" />
                      Copy to Clipboard
                    </button>
                  </div>
                </motion.div>
              )}
            </div>
          </motion.div>
        </motion.div>
      )}
    </AnimatePresence>
  );
};

export default SessionSummaryModal;